[package]
name = "aurora-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
tokio.workspace = true
lofty.workspace = true
mlua.workspace = true
