[package]
name = "aurora-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
slint.workspace = true
image.workspace = true
palette.workspace = true
anyhow.workspace = true
log.workspace = true

[build-dependencies]
slint-build = "1.9.0"
